= Compiler et construire ses applications avec maven
Jean-Michel Bruel <jbruel@gmail.com>
v1, 2022-02-20 : Initial draft
:imagesdir: images
:maven: http://maven.apache.org/[Maven]

== Contenu du TP 

Ce dépôt contient l'entièreté des fichiers sources du TP4. Les fichiers HelloJava.java, Calculette.java et pom.xml ont été modifié.
Le fichier calculette.java est tiré du précédent TP, la javadoc n'a pas ici été générée avec Maven.
Pour faire fonctionner le programme Calculette java, il faut suivre ces étapes : 

	- Premièrement, il faut s'assurer que tout soit bien nettoyer avec la commande : 
			mvn clean
	- Deuxièmement, vous devez compiler le programme en effectuant la commande suivante dans le répertoire où se trouve pom.xml : 
			mvn compile
	- Troisièmement, vous devez créer une version exécutable si elle n'existe pas déjà avec :
			mvn package 
	- Quatrièment, vous êtes prêt à éxecuter le code java avec : 
			java -jar target/tp_qualite-1.0.jar

En cas de problème vous pouvez vous référez à la documentation {maven}.

TP réalisé par LARROUTIS Guillaume. 


